title: CS 195
description: "CS 195: Social Implications of Computer Technology"
collections_dir: collections

url: "fa23.cs195.org"
edstem: https://edstem.org/us/courses/43672/discussion/
bcourses: https://bcourses.berkeley.edu/courses/1528441
ed_zoom_link: TBD
term: Fall 2023
lecture_time: Wednesday 5:00-6:30PM
lecture_room: Evans 10
discussion_time: Thursday 2:00-3:30PM
discussion_room: Soda 606

assignment_time: "11:59pm"
h195_apps_due: "Friday 9/1 11:59pm PT"

theme: minima

exclude:
  - .venv
  - .direnv
  - scripts

collections:
  - cs195_readings
  - csH195_discussions

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
